# Generated by Django 2.2.5 on 2019-09-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='run_time',
            new_name='running_time',
        ),
    ]
